# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.7.0
_src_path: gh:radio-aktywne/template-devcontainer
accountname: radio-aktywne
description: Devcontainer for templates 🧶
devcontainername: template
docs: true
docsurl: https://radio-aktywne.github.io/devcontainer-template
imagename: devcontainers/template
registry: true
releases: true
reponame: devcontainer-template
repourl: https://github.com/radio-aktywne/devcontainer-template
